name: Build

on:
  [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    env:
      BUILD_VERSION: SNAPSHOT
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: bintray-jcenter
          server-username: BINTRAY_USERNAME
          server-password: BINTRAY_API_KEY
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Ensure to use tagged version
        run: mvn versions:set --file ./pom.xml -DnewVersion=${GITHUB_REF##*/}
        if: startsWith(github.ref, 'refs/tags/')
      - name: Export the project version to the job environment and fix it as an ouput of this job
        id: setversion
        run: |
          v=$(mvn help:evaluate "-Dexpression=project.version" -q -DforceStdout)
          echo "BUILD_VERSION=${v}" >> $GITHUB_ENV
      - name: Build and Test
        run: mvn -B clean install jacoco:report -Pcoverage,dependency-check
      - name: Upload code coverage report
        id: codacyCoverageReporter
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        continue-on-error: true
      - name: Upload snapshot artifact siv-mode-${{ env.BUILD_VERSION }}.jar
        uses: actions/upload-artifact@v2
        with:
          name: siv-mode-${{ env.BUILD_VERSION }}
          path: target/siv-mode-${{ env.BUILD_VERSION }}.jar
      - name: Build and deploy to jcenter
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B deploy -DskipTests -Prelease
        env:
          BINTRAY_USERNAME: cryptobot
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
